name: Deploy to Salesforce

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Salesforce CLI
      run: |
        npm install -g @salesforce/cli
        sf --version
        
    - name: Deploy to Salesforce
      run: |
        echo "Deploying Companies House integration to Salesforce..."
        sf project deploy start --source-dir force-app/main/default --manifest companies-house-package.xml
      env:
        SF_LOGIN_URL: ${{ secrets.SF_LOGIN_URL }}
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SF_SECURITY_TOKEN: ${{ secrets.SF_SECURITY_TOKEN }}
        
    - name: Run Tests
      run: |
        echo "Running deployment tests..."
        # Add any additional test commands here
        
    - name: Deployment Summary
      run: |
        echo "✅ Deployment completed successfully!"
        echo "📦 Companies House integration deployed to Salesforce"
        echo "🔑 Remember to configure your API key in the component"
        echo "📖 See README.md for setup instructions" 